apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-service
  description: The service that handles all todo tasks
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-tanzu
  system: todo-system
  providesApi:
    - todo-api
  dependsOn:
    - postgres-db

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-ui
  description: The user interface for todo tasks
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: team-tanzu
  system: todo-system
  consumesApi:
    - todo-api

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgres-db
  description: The Postgres database for todo tasks
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: database
  lifecycle: production
  owner: team-tanzu
  system: todo-system

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: todo-system
  description: The todo system
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: team-tanzu
  domain: todo
