apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: todo-system
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: team-tanzu
  domain: production
  description: The system for managing todo items

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-ui
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-tanzu
  system: todo-system
  description: The user interface for the todo system
  consumesApis:
    - todo-service-api

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-tanzu
  system: todo-system
  description: The backend service for the todo system
  dependsOn:
    - postgres-db
  providesApis:
    - todo-service-api

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: todo-service-api
  description: Backend API for the Todos application
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: team-tanzu
  system: todo-system
  definition: "https://raw.githubusercontent.com/odedia/todo-service/main/openapi.yaml"

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-db
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: database
  lifecycle: production
  owner: team-tanzu
  system: todo-system
  description: The database for storing todo items
