apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-tanzu
  description: The team Tanzu.
spec:
  type: team
  profile:
    displayName: Team Tanzu
    pictureUrl: https://placeimg.com/240/240/nature
  parent: tanzu-domain
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: tanzu-domain
  description: The domain of team Tanzu.
spec: {}
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-ui
  description: The UI for the todo system.
  annotations:
    backstage.io/managed-by-location: url:https://github.com/odedia/todo-service/tree/main/catalog-info.yaml
  labels:
    system: todo-system
    domain: tanzu-domain
  owner: team-tanzu
spec:
  type: website
  lifecycle: production
  providesApis:
    - todo-service-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-service
  description: The service for the todo system.
  annotations:
    backstage.io/managed-by-location: url:https://github.com/odedia/todo-service/tree/main/catalog-info.yaml
  labels:
    system: todo-system
    domain: tanzu-domain
  owner: team-tanzu
spec:
  type: service
  lifecycle: production
  consumesApis:
    - todo-service-api
  dependsOn:
    - postgres-db
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: todo-service-api
  description: The API for the todo-service component.
  annotations:
    backstage.io/managed-by-location: url:https://github.com/odedia/todo-service/tree/main/catalog-info.yaml
  labels:
    system: todo-system
    domain: tanzu-domain
  owner: team-tanzu
spec:
  type: openapi
  lifecycle: production
  owner: team-tanzu
  system: todo-system
  definitionAtLocation: url:https://raw.githubusercontent.com/odedia/todo-service/main/catalog/todo-api.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-db
  description: The Postgres database for the todo system.
  annotations:
    backstage.io/managed-by-location: url:https://github.com/odedia/todo-service/tree/main/catalog-info.yaml
  labels:
    system: todo-system
    domain: tanzu-domain
  owner: team-tanzu
spec:
  type: database
