#@ load("@ytt:data", "data")
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: todos-gateway
spec:
  service:
    type: ClusterIP
  api:
    title: Todos Gateway
    description: The entrypoint for the Todos application
    version: 1.0.0
    serverUrl: #@ "https://todos.{}".format(data.values.ingress.fqdn)
  env:
    - name: spring.cloud.gateway.httpclient.connect-timeout
      value: "90"
