#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: todos-proxy
spec:
  virtualhost:
    fqdn: todos.apps.tap16.tanzutime.com
  routes:
  - services:
    - name: todos-gateway
      port: 80
    conditions:
      - prefix: /
