#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: todos-proxy
spec:
  virtualhost:
    fqdn: #@ "todos.{}".format(data.values.ingress.domain)
    tls: 
      secretName: #@ "tanzu-system-ingress/{}".format(data.values.ingress.contour_tls_secret)
  routes:
  - services:
    - name: todos-gateway
      port: 80
    conditions:
      - prefix: /
