apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: todos-db
  namespace: service-instances
spec:
  pgConfig:
    dbname: todos-db
    username: pgadmin
    appUser: pgappuser
  postgresVersion:
    name: postgres-14
  serviceType: LoadBalancer
  seccompProfile:
    type: RuntimeDefault
  imagePullSecret:
    name: regsecret
  resources:
    monitor:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 800m
        memory: 800Mi
    metrics:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
