#@ load("@ytt:data","data")
---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: #@ data.values.dbName
spec:
  memory: 800Mi
  cpu: "0.8"
  storageClassName: vc01cl01-t0compute
  monitorStorageClassName: vc01cl01-t0compute
  storageSize: 10G
  pgConfig:
    dbname: #@ data.values.dbName
    username: pgadmin
    appUser: tanzu
